---
apiVersion: v1
kind: Service
metadata:
  name: arbitr-sql
  labels:
    team: elite
    app: arbitr-sql
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: arbitr-sql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arbitr-sql
  labels:
    team: elite
spec:
  serviceName: arbitr-sql
  selector:
    matchLabels:
      app: arbitr-sql
  replicas: 1
  template:
    metadata:
      labels:
        app: arbitr-sql
        team: elite
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: arbitr-sql
        image: skaffold-dev/arbitr.db
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arbitr-sql
              key: SA_PASSWORD
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "sleep 10; /opt/mssql-tools/bin/sqlcmd -s localhost -U SA -P $SA_PASSWORD -i init.sql"]
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /opt/mssql-tools/bin/sqlcmd -s localhost -U SA -P $SA_PASSWORD -Q " select 1 "
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: microsoft-regcred
---
